module.exports = {
    arrowParens: "always",
    bracketSpacing: true,
    cursorOffset: -1,
    embeddedLanguageFormatting: "auto",
    endOfLine: "lf",
    htmlWhitespaceSensitivity: "css",
    insertPragma: false,
    jsxSingleQuote: false,
    proseWrap: "preserve",
    quoteProps: "as-needed",
    rangeStart: 0,
    requirePragma: false,
    singleAttributePerLine: false,
    trailingComma: "all",
    useTabs: false,
    vueIndentScriptAndStyle: false,
    semi: true,
    singleQuote: false,
    printWidth: 90,
    tabWidth: 4,
    bracketSameLine: true,
};
